/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CadastroUsuarioController;
import Dao.Conexao;
import Dao.UsuarioDao;
import Model.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author caiot
 */
public class CadastroUsuarioView extends javax.swing.JFrame {
    private final CadastroUsuarioController cadastroUsuarioController;
    /**
     * Creates new form Home
     */
    public CadastroUsuarioView() {
        initComponents();
        cadastroUsuarioController = new CadastroUsuarioController(this);
    }

    public JPasswordField getjPasswordSenhaCadastroUsuario() {
        return jPasswordSenhaCadastroUsuario;
    }

    public void setjPasswordSenhaCadastroUsuario(JPasswordField jPasswordSenhaCadastroUsuario) {
        this.jPasswordSenhaCadastroUsuario = jPasswordSenhaCadastroUsuario;
    }

    public JRadioButton getjRadioButtonFisicaCadastroUsuario() {
        return jRadioButtonFisicaCadastroUsuario;
    }

    public void setjRadioButtonFisicaCadastroUsuario(JRadioButton jRadioButtonFisicaCadastroUsuario) {
        this.jRadioButtonFisicaCadastroUsuario = jRadioButtonFisicaCadastroUsuario;
    }

    public JRadioButton getjRadioButtonJuridicaCadastroUsuario() {
        return jRadioButtonJuridicaCadastroUsuario;
    }

    public void setjRadioButtonJuridicaCadastroUsuario(JRadioButton jRadioButtonJuridicaCadastroUsuario) {
        this.jRadioButtonJuridicaCadastroUsuario = jRadioButtonJuridicaCadastroUsuario;
    }

    public JTextField getjTextFieldEmailCadastroUsuario() {
        return jTextFieldEmailCadastroUsuario;
    }

    public void setjTextFieldEmailCadastroUsuario(JTextField jTextFieldEmailCadastroUsuario) {
        this.jTextFieldEmailCadastroUsuario = jTextFieldEmailCadastroUsuario;
    }

    public JTextField getjTextFieldUsuarioCadastroUsuario() {
        return jTextFieldUsuarioCadastroUsuario;
    }

    public void setjTextFieldUsuarioCadastroUsuario(JTextField jTextFieldUsuarioCadastroUsuario) {
        this.jTextFieldUsuarioCadastroUsuario = jTextFieldUsuarioCadastroUsuario;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuarioCadastroUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmailCadastroUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonFisicaCadastroUsuario = new javax.swing.JRadioButton();
        jRadioButtonJuridicaCadastroUsuario = new javax.swing.JRadioButton();
        jToggleButtonSalvarCadastroUsuario = new javax.swing.JToggleButton();
        jToggleButtonVoltarCadastroUsuario = new javax.swing.JToggleButton();
        jPasswordSenhaCadastroUsuario = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));

        jLabel3.setText("Usuário");

        jLabel4.setText("Senha");

        jLabel5.setText("Email");

        jLabel6.setText("Pessoa");

        jRadioButtonFisicaCadastroUsuario.setText("Física");

        jRadioButtonJuridicaCadastroUsuario.setText("Jurídica");
        jRadioButtonJuridicaCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuridicaCadastroUsuarioActionPerformed(evt);
            }
        });

        jToggleButtonSalvarCadastroUsuario.setText("Salvar");
        jToggleButtonSalvarCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSalvarCadastroUsuarioActionPerformed(evt);
            }
        });

        jToggleButtonVoltarCadastroUsuario.setText("Voltar");
        jToggleButtonVoltarCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVoltarCadastroUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadastro Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonFisicaCadastroUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonJuridicaCadastroUsuario))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButtonSalvarCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButtonVoltarCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEmailCadastroUsuario)
                            .addComponent(jTextFieldUsuarioCadastroUsuario)
                            .addComponent(jPasswordSenhaCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addGap(0, 256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuarioCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordSenhaCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldEmailCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFisicaCadastroUsuario)
                    .addComponent(jRadioButtonJuridicaCadastroUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonSalvarCadastroUsuario)
                    .addComponent(jToggleButtonVoltarCadastroUsuario))
                .addGap(0, 279, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonJuridicaCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuridicaCadastroUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonJuridicaCadastroUsuarioActionPerformed

    private void jToggleButtonSalvarCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSalvarCadastroUsuarioActionPerformed
        cadastroUsuarioController.salvaUsuario();        
    }//GEN-LAST:event_jToggleButtonSalvarCadastroUsuarioActionPerformed

    private void jToggleButtonVoltarCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVoltarCadastroUsuarioActionPerformed
        LoginView telaLogin = new LoginView();
        telaLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButtonVoltarCadastroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordSenhaCadastroUsuario;
    private javax.swing.JRadioButton jRadioButtonFisicaCadastroUsuario;
    private javax.swing.JRadioButton jRadioButtonJuridicaCadastroUsuario;
    private javax.swing.JTextField jTextFieldEmailCadastroUsuario;
    private javax.swing.JTextField jTextFieldUsuarioCadastroUsuario;
    private javax.swing.JToggleButton jToggleButtonSalvarCadastroUsuario;
    private javax.swing.JToggleButton jToggleButtonVoltarCadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
