/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

<<<<<<< HEAD
=======
import Model.Usuario;

>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
/**
 *
 * @author caiot
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
<<<<<<< HEAD
     */
=======
     * @param usuario
     */
    private Usuario usuario;
    
    public HomeView(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }
    
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarItemHome = new javax.swing.JButton();
        jButtonAlterarItemHome = new javax.swing.JButton();
        jButtonExcluirItemHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonLogoutHome = new javax.swing.JButton();
<<<<<<< HEAD
=======
        jButtonPesquisarItemHome = new javax.swing.JButton();
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));

        jButtonCadastrarItemHome.setText("Cadastrar Item");
        jButtonCadastrarItemHome.setMaximumSize(new java.awt.Dimension(81, 23));
        jButtonCadastrarItemHome.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonCadastrarItemHome.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonCadastrarItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarItemHomeActionPerformed(evt);
            }
        });

        jButtonAlterarItemHome.setText("Alterar Item");
        jButtonAlterarItemHome.setMaximumSize(new java.awt.Dimension(81, 23));
        jButtonAlterarItemHome.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonAlterarItemHome.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonAlterarItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarItemHomeActionPerformed(evt);
            }
        });

        jButtonExcluirItemHome.setText("Excluir Item");
        jButtonExcluirItemHome.setMaximumSize(new java.awt.Dimension(81, 23));
        jButtonExcluirItemHome.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonExcluirItemHome.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonExcluirItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirItemHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciamento de Itens");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonLogoutHome.setText("Logout");
        jButtonLogoutHome.setMaximumSize(new java.awt.Dimension(81, 23));
        jButtonLogoutHome.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonLogoutHome.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonLogoutHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutHomeActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
        jButtonPesquisarItemHome.setText("Pesquisar Item");
        jButtonPesquisarItemHome.setMaximumSize(new java.awt.Dimension(81, 23));
        jButtonPesquisarItemHome.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonPesquisarItemHome.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonPesquisarItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarItemHomeActionPerformed(evt);
            }
        });

>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
<<<<<<< HEAD
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
=======
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(217, 217, 217))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogoutHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
<<<<<<< HEAD
=======
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastrarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluirItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
=======
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisarItemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
                .addComponent(jButtonLogoutHome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarItemHomeActionPerformed
<<<<<<< HEAD
        CadastroItemView telaCadastroItem = new CadastroItemView();
=======
        CadastroItemView telaCadastroItem = new CadastroItemView(usuario);
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
        telaCadastroItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadastrarItemHomeActionPerformed

    private void jButtonAlterarItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarItemHomeActionPerformed
<<<<<<< HEAD
        AlterarItemView telaAlterarItem = new AlterarItemView();
=======
        AlterarItemView telaAlterarItem = new AlterarItemView(usuario);
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
        telaAlterarItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAlterarItemHomeActionPerformed

    private void jButtonExcluirItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirItemHomeActionPerformed
<<<<<<< HEAD
        ExcluirItemView telaExcluirItem = new ExcluirItemView();
=======
        ExcluirItemView telaExcluirItem = new ExcluirItemView(usuario);
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
        telaExcluirItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonExcluirItemHomeActionPerformed

    private void jButtonLogoutHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutHomeActionPerformed
        LoginView login = new LoginView();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonLogoutHomeActionPerformed

<<<<<<< HEAD
=======
    private void jButtonPesquisarItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarItemHomeActionPerformed
        PesquisarItemView telaPesquisarItem = new PesquisarItemView(usuario);
        telaPesquisarItem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonPesquisarItemHomeActionPerformed

>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarItemHome;
    private javax.swing.JButton jButtonCadastrarItemHome;
    private javax.swing.JButton jButtonExcluirItemHome;
    private javax.swing.JButton jButtonLogoutHome;
<<<<<<< HEAD
=======
    private javax.swing.JButton jButtonPesquisarItemHome;
>>>>>>> c926bfd7501ee4d3d2f4df9b97ce259c3b03b07a
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
