package View;

import Controller.LoginController;
import java.sql.SQLException;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author caiot
 */
public class LoginView extends javax.swing.JFrame {
    private final LoginController loginController;
    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
        loginController = new LoginController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextUsuarioLogin = new javax.swing.JTextField();
        TextSenhaLogin = new javax.swing.JPasswordField();
        jButtonEntrarLogin = new javax.swing.JButton();
        jButtonCadastrarLogin = new javax.swing.JButton();
        jLabelPainelLogin = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(600, 600));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Usuário");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 50, 30));

        jLabel4.setText("Senha");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 50, 30));

        TextUsuarioLogin.setMinimumSize(new java.awt.Dimension(34, 14));
        TextUsuarioLogin.setPreferredSize(new java.awt.Dimension(34, 14));
        jDesktopPane1.add(TextUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 190, 27));

        TextSenhaLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextSenhaLogin.setMinimumSize(new java.awt.Dimension(34, 14));
        TextSenhaLogin.setPreferredSize(new java.awt.Dimension(34, 14));
        TextSenhaLogin.setSelectedTextColor(java.awt.Color.black);
        jDesktopPane1.add(TextSenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 190, 27));

        jButtonEntrarLogin.setText("Entrar");
        jButtonEntrarLogin.setMaximumSize(new java.awt.Dimension(81, 23));
        jButtonEntrarLogin.setMinimumSize(new java.awt.Dimension(81, 23));
        jButtonEntrarLogin.setPreferredSize(new java.awt.Dimension(81, 23));
        jButtonEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarLoginActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonEntrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 90, 25));

        jButtonCadastrarLogin.setText("Cadastrar");
        jButtonCadastrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarLoginActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonCadastrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 90, 25));

        jLabelPainelLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\caiot\\Documents\\NetBeansProjects\\sistemaDoacoes\\src\\main\\java\\View\\imagem\\fundoCinza.jpg")); // NOI18N
        jDesktopPane1.add(jLabelPainelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 430, 520, 110));

        jLabelFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\caiot\\Documents\\NetBeansProjects\\sistemaDoacoes\\src\\main\\java\\View\\imagem\\SistemaDoacao.png")); // NOI18N
        jLabelFundo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFundo.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabelFundo.setMinimumSize(new java.awt.Dimension(600, 600));
        jLabelFundo.setNextFocusableComponent(jLabelFundo);
        jLabelFundo.setPreferredSize(new java.awt.Dimension(600, 600));
        jDesktopPane1.add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarLoginActionPerformed
        try {
            loginController.autenticar();
        } catch (SQLException ex) {
            loginController.erroAutenticacao();
        }
    }//GEN-LAST:event_jButtonEntrarLoginActionPerformed

    private void jButtonCadastrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarLoginActionPerformed
        CadastroUsuarioView telaCadastroUsuario = new CadastroUsuarioView();
        telaCadastroUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCadastrarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    public JPasswordField getTextSenhaLogin() {
        return TextSenhaLogin;
    }

    public void setTextSenhaLogin(JPasswordField TextSenhaLogin) {
        this.TextSenhaLogin = TextSenhaLogin;
    }

    public JTextField getTextUsuarioLogin() {
        return TextUsuarioLogin;
    }

    public void setTextUsuarioLogin(JTextField TextUsuarioLogin) {
        this.TextUsuarioLogin = TextUsuarioLogin;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField TextSenhaLogin;
    private javax.swing.JTextField TextUsuarioLogin;
    private javax.swing.JButton jButtonCadastrarLogin;
    private javax.swing.JButton jButtonEntrarLogin;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelPainelLogin;
    // End of variables declaration//GEN-END:variables
}
